services: docker
php:
- 7.0
env:
  DOCKER_COMPOSE_VERSION: 1.7.0
before_install:
  # Upgrade docker/docker-compose versions so we can use v2 of the Dockerfile format
  - docker -v
  - sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine
  - docker -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Use the env config
  - cp .env.example .env
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # Start the docker stuff
  - docker-compose -v
  #- docker-compose up -d
  #- sleep 4
  #- docker-compose ps
install:
  # build cron container
  - docker build -t "bkuhl/biblebowl:nginx.${TRAVIS_COMMIT::8}" -f containers/nginx/Dockerfile .
  - docker build -t "bkuhl/biblebowl:cli.${TRAVIS_COMMIT::8}" -f containers/cli/Dockerfile .
  - docker build -t "bkuhl/biblebowl:queue.${TRAVIS_COMMIT::8}" -f containers/queue/Dockerfile .
  - docker build -t "bkuhl/biblebowl:fpm.${TRAVIS_COMMIT::8}" -f containers/fpm/Dockerfile .
  #- docker exec -it $(docker-compose ps -q fpm) ls -latr /var/www
  # Install dev php dependencies
  #- docker exec -it $(docker-compose ps -q fpm) composer install --no-interaction --prefer-dis
  #- docker exec -it $(docker-compose ps -q fpm) ls -latr /var/www/html/vendor
script:
  # Push deployable images
  - docker images
  #- docker tag "bkuhl/biblebowl:fpm" "bkuhl/biblebowl:fpm.${TRAVIS_COMMIT::8}" && docker push "bkuhl/biblebowl:fpm.${TRAVIS_COMMIT::8}"
  - docker push "bkuhl/biblebowl:nginx.${TRAVIS_COMMIT::8}"
  - docker push "bkuhl/biblebowl:cli.${TRAVIS_COMMIT::8}"
  - docker push "bkuhl/biblebowl:queue.${TRAVIS_COMMIT::8}"
  - docker push "bkuhl/biblebowl:fpm.${TRAVIS_COMMIT::8}"
  #- docker exec -it $(docker-compose ps -q fpm) ls -latr /var/www/html
  # Seed database
  #- docker exec -it $(docker-compose ps -q fpm) php artisan migrate --seed
  # Run tests
  #- docker exec -it $(docker-compose ps -q fpm) /var/www/html/vendor/bin/phpunit
after_success: