services: docker
before_install:
  - docker -v
  # Use the env config
  - cp .env.example .env
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
  # Start the docker stuff
  - docker-compose up -d
  - sleep 8
  # Install dev php dependencies
  - docker-compose exec web sh -c "composer install --no-interaction --prefer-dist"
script:
  # Seed database
  - docker-compose exec web sh -c "php artisan migrate --seed"
  # Run tests
  - docker-compose exec web sh -c "composer test"
  # Build cli container
  - docker build -t "bkuhl/biblebowl:cli" -f infrastructure/cli/Dockerfile .
after_success:
  # Deployable image tags must be in format: web-latest, cli-latest, nginx-latest
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then docker tag "bkuhl/biblebowl:web" "bkuhl/biblebowl:web-latest" && docker push "bkuhl/biblebowl:web-latest" ; fi
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then docker tag "bkuhl/biblebowl:cli" "bkuhl/biblebowl:cli-latest" && docker push "bkuhl/biblebowl:cli-latest" ; fi