services: docker
before_install:
  - docker -v
  # Use the env config
  - cp .env.example .env
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
  # Start the docker stuff
  - docker-compose up -d
  - sleep 8
  # Install dev php dependencies
  - docker-compose exec fpm sh -c "composer install --no-interaction --prefer-dist"
script:
#  - mysql -u biblebowl -p biblebowl -e "select * from biblebowl_account.users"
  # Seed database
  - docker-compose exec fpm sh -c "php artisan migrate --seed"
  # Run tests
  - docker-compose exec fpm sh -c "composer test"
  # Build cli container
  - docker build -t "bkuhl/biblebowl:cli" -f infrastructure/cli/Dockerfile .
after_success:
  # Deployable image tags must be in format: fpm-latest, cli-latest, nginx-latest
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master') ]]; then docker tag "bkuhl/biblebowl:fpm" "bkuhl/biblebowl:fpm.${TRAVIS_COMMIT::8}" && docker push "bkuhl/biblebowl:fpm.${TRAVIS_COMMIT::8}" ; fi
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master') ]]; then docker tag "bkuhl/biblebowl:nginx" "bkuhl/biblebowl:fpm-latest" && docker push "bkuhl/biblebowl:fpm-latest" ; fi
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master') ]]; then docker tag "bkuhl/biblebowl:cli" "bkuhl/biblebowl:cli.${TRAVIS_COMMIT::8}" && docker push "bkuhl/biblebowl:cli.${TRAVIS_COMMIT::8}" ; fi
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master') ]]; then docker tag "bkuhl/biblebowl:nginx" "bkuhl/biblebowl:cli-latest" && docker push "bkuhl/biblebowl:cli-latest" ; fi
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master') ]]; then docker tag "bkuhl/biblebowl:nginx" "bkuhl/biblebowl:nginx.${TRAVIS_COMMIT::8}" && docker push "bkuhl/biblebowl:nginx.${TRAVIS_COMMIT::8}" ; fi
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master') ]]; then docker tag "bkuhl/biblebowl:nginx" "bkuhl/biblebowl:nginx-latest" && docker push "bkuhl/biblebowl:nginx-latest" ; fi