version: '2'

services:
  web:
    build:
      context: .
      dockerfile: infrastructure/web/Dockerfile
    image: bkuhl/biblebowl:web
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./infrastructure/web:/etc/nginx/conf.d
    links:
      - db
    ports:
      - "80:80"
  redis:
    image: redis:3-alpine
    ports:
      - "6379:6379"
  db:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: biblebowl_account
      MYSQL_USER: biblebowl
      MYSQL_PASSWORD: biblebowl