version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: containers/fpm/Dockerfile
    image: bkuhl/biblebowl:fpm
    env_file: .env
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:1.9-alpine
    volumes_from:
      - fpm
    volumes:
      - ./containers/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"
  db:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: biblebowl
      MYSQL_DATABASE: biblebowl_account
      MYSQL_USER: biblebowl
      MYSQL_PASSWORD: biblebowl