<?php

$names = '';
if (count($playerNames) == 1) {
    $names = $playerNames[0];
} else {
    $lastName = array_pop($playerNames);
    if (count($playerNames) > 1) {
        $names = implode(', ', $playerNames);
    }
    $names .= ' and '.$lastName;
}

?>
<h4>Terms of Participation</h4>
<p>I, {{ $user->full_name }}, the parent or legal guardian of {{ $names }} (“Participants”), certify that they have my full approval to participate in Bible Bowl Events (“Events”) for the full duration of the {{ $season->name }} season.</p>
<p>I understand that all individuals participating in Events are expected to abide by the Event’s rules and be directly responsible to the Event Coordinators (“Event Coordinators”) which may include the representatives of the Board of Directors of National Bible Bowl (“National Bible Bowl”).</p>
<p>Event Coordinators assume responsibility for discipline at Tournaments and, if necessary may, in their sole and absolute discretion, because of misconduct or disobedience, disqualify an individual from any competition. In such an instance, I will automatically assume full responsibility for returning the Participant home. The sponsor who brought the Participant, Participant, parent, guardian (including members of Participant’s family) hereby voluntarily releases Event Coordinators, National Bible Bowl, its employees, agents, managers, directors, volunteers, officers, and representatives, including any owner or lessor of any property or land on which the Program is held (collectively, its “Affiliates”) from any and all liability, claims, demands, actions or rights of action, which are related to or in any way connected with Participant’s engagement in the Program. This release includes specifically, but is not limited to, the negligent acts or omissions of Event Coordinators, National Bible Bowl and its Affiliates. I agree to pay for any damages or property loss as determined by Event Coordinators, National Bible Bowl or Hotel/Convention officials.</p>
<p>In the event that an emergency arises involving a Participant, I understand that all attempts will be made to contact Participant's parents, legal guardians or sponsors.</p>
<p>I acknowledge that it is the responsibility of parents or legal guardians to provide written permission allowing sponsor(s) with Participants, Program staff and/or volunteers to seek emergency medical or surgical treatment at the nearest medical facility for the minor Participant. Event Coordinators, National Bible Bowl and its Affiliates assume no financial responsibility for any medical expenses incurred by any Participant. Participant further agrees, promises and covenants to not sue, assert or otherwise maintain or assert any claim against National Bible Bowl or its Affiliates for any injury, death or damage to Participant or Participant’s property, arising from or connected with Participant’s engagement in the Program or from any claim asserted against Participant by other third parties. IN SIGNING THIS DOCUMENT, PARTICIPANT FULLY RECOGNIZES THAT IF PARTICIPANT IS HURT OR PROPERTY OF PARTICIPANT IS DAMAGED WHILE ENGAGED IN THE EVENT, PARTICIPANT WILL HAVE NO RIGHT TO MAKE A CLAIM OR FILE A  LAWSUIT AGAINST EVENT COORDINATORS,  NATIONAL BIBLE BOWL OR ITS AFFILIATES.</p>
<p>Participant, intending to be legally bound, hereby voluntarily and knowingly grants to Event Coordinators, National Bible Bowl and its Affiliates in connection with the Event the perpetual right and permission  to use, manipulate, submit, and upload to any electronic medium (including but not limited to all social media websites now or hereafter known) associated with or utilized by National Bible Bowl any and all photographs, videos or audio recordings (collectively, “Recordings”) taken of Particpants or in which Participants may be included with outers, while engaged in the Event, to copyright the same, in National Bible Bowl’s own name or to otherwise use, re-use,  pubilsh, and re-publish the same in whole or in part, individually or in conjunction with other  Recordings, in any and all media now or hereafter known, for promotional or advertising  purposes.</p>
<p>Participant has the right to opt out of National Bible Bowl’s use of Recordings that include  Participant. To exercise this right, Participant must send a written request to the National Bible  Office. Written requests must be received no later than 30 days prior to the beginning of the Event. Absent a written request, notwithstanding the foregoing, Participant  hereby releases and discharges National Bible Bowl and its Affiliates from any and all claims  and demands arising out of or in connection with the use of the Recordings, including, without  limitation, any and all claims for libel or invasion of privacy.</p>
<p>Participant acknowledges that National Bible Bowl may release the names and contact  information (including, but not limited to, physical address, telephone number, email address) of  Participants to certain colleges and universities associated with National Bible Bowl and the  Program.  Participant as the right to opt out of National Bible Bowl’s release of this information  by sending a written request to the National Bible office at the address listed above, no later than 30 days prior to the beginning of the Event. Absent a written request, notwithstanding the foregoing, Participant hereby releases and discharges National Bible Bowl and its Affiliates from any and all claims and  demands arising out of or in connection with the dissemination of Participant’s information.</p>
<p>I certify that all information provided for Participants is true and accurate and that any false statements will disqualify Participants from any competitions at the Event (and consequently the eligibility of any team with which they may be registered).</p>
<p>By registering Participants for the {{ $season->name }} season, I acknowledge that this release constitutes a legal, binding and enforceable agreement and that I have read it carefully and agree to the information given in this form.</p>